# Generated by Django 5.2.17 on 2026-09-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_iri', models.CharField(default='http://primeontology.ai/onto#', max_length=500)),
                ('context', models.CharField(blank=True, default='', max_length=50)),
                ('tenant', models.CharField(blank=True, default='', max_length=100)),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('current_version', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MappingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mappings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_sets', to='prime_ontology.ontology')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('actor', models.CharField(blank=True, default='', max_length=200)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ontology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='prime_ontology.ontology')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QueryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField()),
                ('kind', models.CharField(default='sparql', max_length=20)),
                ('saved', models.BooleanField(default=False)),
                ('result_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='prime_ontology.ontology')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OntologyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prime_ontology.ontology')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('ontology', 'number')},
            },
        ),
    ]
