# Generated by Django 5.2.17 on 2026-10-01 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_ontology', '0002_alter_ontology_status_alter_ontologyversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontology',
            name='base_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ontology',
            name='base_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ontology',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ontology',
            name='branch_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='prime_ontology.ontology'),
        ),
        migrations.AddField(
            model_name='ontology',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ontology',
            name='model_revision',
            field=models.IntegerField(default=1),
        ),
    ]
