# Generated by Django 5.2.17 on 2026-10-01 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_ontology', '0003_ontology_base_snapshot_ontology_base_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, default='', max_length=300)),
                ('canonical', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=10)),
                ('origin', models.CharField(default='fabric', max_length=10)),
                ('record_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absorbed', to='prime_ontology.fabricentity')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_entities', to='prime_ontology.ontology')),
            ],
        ),
        migrations.CreateModel(
            name='FabricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, default='', max_length=40)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('link_reason', models.JSONField(default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('seen_run', models.IntegerField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='prime_ontology.fabricentity')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_records', to='prime_ontology.ontology')),
            ],
        ),
        migrations.CreateModel(
            name='FabricConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=6)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_ontology.ontology')),
                ('record_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prime_ontology.fabricrecord')),
                ('record_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prime_ontology.fabricrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FabricRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=100)),
                ('target_class', models.CharField(max_length=100)),
                ('target_external_id', models.CharField(max_length=255)),
                ('target_source', models.CharField(blank=True, default='', max_length=120)),
                ('from_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refs_out', to='prime_ontology.fabricrecord')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_ontology.ontology')),
                ('to_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refs_in', to='prime_ontology.fabricrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FabricSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=30)),
                ('config', models.JSONField(default=dict)),
                ('secret_enc', models.TextField(blank=True, default='')),
                ('mapping', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(default=0)),
                ('freshness_sla_minutes', models.IntegerField(default=1440)),
                ('priority', models.IntegerField(default=50)),
                ('watermark', models.JSONField(default=dict)),
                ('last_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('running_since', models.DateTimeField(blank=True, null=True)),
                ('full_every', models.IntegerField(default=24)),
                ('sync_count', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_sources', to='prime_ontology.ontology')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fabricrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='prime_ontology.fabricsource'),
        ),
        migrations.CreateModel(
            name='FabricDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=120)),
                ('inferred_type', models.CharField(default='string', max_length=20)),
                ('sample', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_drift', to='prime_ontology.ontology')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift', to='prime_ontology.fabricsource')),
            ],
        ),
        migrations.CreateModel(
            name='FabricState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('ontology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_state', to='prime_ontology.ontology')),
            ],
        ),
        migrations.CreateModel(
            name='FabricSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('reasons', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('decided_by', models.CharField(blank=True, default='', max_length=200)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prime_ontology.fabricentity')),
                ('entity_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prime_ontology.fabricentity')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_suggestions', to='prime_ontology.ontology')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='FabricSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='incremental', max_length=12)),
                ('trigger', models.CharField(default='manual', max_length=12)),
                ('status', models.CharField(default='running', max_length=12)),
                ('stats', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('actor', models.CharField(blank=True, default='', max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='prime_ontology.fabricsource')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FabricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='prime_ontology.fabricentity')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_events', to='prime_ontology.ontology')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='prime_ontology.fabricrecord')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='prime_ontology.fabricsource')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='prime_ontology.fabricsyncrun')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FabricToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=190)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_ontology.ontology')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='prime_ontology.fabricrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='fabricentity',
            index=models.Index(fields=['ontology', 'class_name', 'status'], name='prime_ontol_ontolog_e940d4_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricentity',
            index=models.Index(fields=['ontology', 'display_name'], name='prime_ontol_ontolog_a57988_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricref',
            index=models.Index(fields=['ontology', 'target_class', 'target_external_id'], name='prime_ontol_ontolog_f720ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fabricref',
            unique_together={('from_record', 'property', 'target_class', 'target_external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='fabricsource',
            unique_together={('ontology', 'name')},
        ),
        migrations.AddIndex(
            model_name='fabricrecord',
            index=models.Index(fields=['ontology', 'class_name', 'deleted'], name='prime_ontol_ontolog_5b94f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fabricrecord',
            unique_together={('source', 'class_name', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='fabricdrift',
            unique_together={('source', 'class_name', 'field')},
        ),
        migrations.AddIndex(
            model_name='fabrictoken',
            index=models.Index(fields=['ontology', 'class_name', 'token'], name='prime_ontol_ontolog_3371a3_idx'),
        ),
    ]
