# Generated by Django 5.2.17 on 2026-10-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_ontology', '0004_fabricentity_fabricrecord_fabricconstraint_fabricref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source_uri', models.CharField(blank=True, default='', max_length=500)),
                ('doc_type', models.CharField(blank=True, default='document', max_length=40)),
                ('classification', models.CharField(default='internal', max_length=14)),
                ('metadata', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, default='', max_length=40)),
                ('chunk_count', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_documents', to='prime_ontology.ontology')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RagChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(default=0)),
                ('heading', models.CharField(blank=True, default='', max_length=300)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('concepts', models.JSONField(default=list)),
                ('entities', models.JSONField(default=list)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('embedding_provider', models.CharField(blank=True, default='', max_length=40)),
                ('classification', models.CharField(default='internal', max_length=14)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to='prime_ontology.ontology')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='prime_ontology.ragdocument')),
            ],
            options={
                'indexes': [models.Index(fields=['ontology', 'classification'], name='prime_ontol_ontolog_d783ff_idx')],
            },
        ),
    ]
