# Generated by Django 5.2.17 on 2026-10-01 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_ontology', '0005_ragdocument_ragchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwinAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(default='asset', max_length=60)),
                ('attributes', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='prime_ontology.fabricentity')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_assets', to='prime_ontology.ontology')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='prime_ontology.twinasset')),
            ],
        ),
        migrations.CreateModel(
            name='TwinEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.CharField(default='api', max_length=60)),
                ('actor', models.CharField(blank=True, default='', max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twin_events', to='prime_ontology.fabricentity')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_events', to='prime_ontology.ontology')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TwinProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('entity_class', models.CharField(max_length=100)),
                ('states', models.JSONField(default=list)),
                ('initial', models.CharField(max_length=60)),
                ('transitions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_processes', to='prime_ontology.ontology')),
            ],
            options={
                'unique_together': {('ontology', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TwinAttributeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=100)),
                ('value', models.JSONField(null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='fabric', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='prime_ontology.fabricentity')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_history', to='prime_ontology.ontology')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'property', 'valid_from'], name='prime_ontol_entity__ebb178_idx'), models.Index(fields=['ontology', 'valid_to'], name='prime_ontol_ontolog_ee45c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TwinProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
                ('history', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_instances', to='prime_ontology.fabricentity')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='prime_ontology.twinprocess')),
            ],
            options={
                'unique_together': {('process', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='TwinRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('class_name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=10)),
                ('target', models.CharField(blank=True, default='', max_length=100)),
                ('expression', models.CharField(max_length=600)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('severity', models.CharField(default='warning', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_rules', to='prime_ontology.ontology')),
            ],
            options={
                'unique_together': {('ontology', 'name')},
            },
        ),
    ]
