# Generated by Django 5.2.17 on 2026-10-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_ontology', '0007_agent_agentmemory_agentrun_agentstep_agentevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='prime_ontology.fabricsource')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'processed', 'class_name'], name='prime_ontol_source__76eef4_idx')],
            },
        ),
    ]
