from django.urls import path

from . import auth_views as a
from . import branch_views as br
from . import views as v
from .fabric import views as fb
from .rag import views as rg
from .twin import views as tw
from .autonomy import views as ag
from .fabric import views as fb

_routes = [
    path("auth/login/", a.auth_login),
    path("auth/logout/", a.auth_logout),
    path("auth/me/", a.auth_me),
    path("health/", v.health),
    path("supported/", v.supported),
    path("inspect/", v.inspect_source),
    path("generate/", v.generate),
    path("ingest/", v.ingest_file),
    path("ingest-url/", v.ingest_url),
    path("embedded/manifest/", v.embedded_manifest),
    path("embedded/context/", v.embedded_context),
    path("embedded/event/", v.embedded_event),
    path("", v.ontology_list),
    path("<int:pk>/", v.ontology_detail),
    path("<int:pk>/export/", v.ontology_export),
    path("<int:pk>/graph/", v.graph),
    path("<int:pk>/validate/", v.validate_view),
    path("<int:pk>/reason/", v.reason_view),
    path("<int:pk>/shapes/", v.shapes_view),
    path("<int:pk>/shacl/", v.shacl_view),
    path("<int:pk>/search/", v.search_view),
    path("<int:pk>/concepts/<str:name>/", v.concept_view),
    path("<int:pk>/path/", v.path_view),
    path("<int:pk>/query/", v.query_view),
    path("<int:pk>/queries/", v.queries_view),
    path("<int:pk>/queries/<int:qid>/", v.query_delete),
    path("<int:pk>/mapping/extract/", v.mapping_extract),
    path("<int:pk>/mapping/propose/", v.mapping_propose),
    path("<int:pk>/mappings/", v.mapping_sets),
    path("<int:pk>/mappings/<int:mid>/", v.mapping_set_detail),
    path("<int:pk>/mappings/<int:mid>/commit/", v.mapping_commit),
    path("<int:pk>/versions/", v.versions_view),
    path("<int:pk>/versions/<str:number>/", v.version_detail),
    path("<int:pk>/versions/<str:number>/<str:action>/", v.version_action),
    path("<int:pk>/diff/", v.diff_view),
    path("<int:pk>/audit/", v.audit_view),
    path("<int:pk>/branches/", br.branches),
    path("<int:pk>/merge/", br.merge),
    path("<int:pk>/ai/", v.ai_propose),
    path("<int:pk>/ai/apply/", v.ai_apply),
    path("<int:pk>/agentic/", v.agentic_registry),
    path("<int:pk>/agent/plan/", v.agent_plan),
    path("<int:pk>/agent/context/", v.agent_context),
    path("<int:pk>/rag/documents/", rg.documents),
    path("<int:pk>/rag/documents/<int:did>/", rg.document_detail),
    path("<int:pk>/rag/retrieve/", rg.retrieve_view),
    path("<int:pk>/rag/ask/", rg.ask_view),
    path("<int:pk>/rag/reindex/", rg.reindex_view),
    path("<int:pk>/autonomous/manifest/", ag.autonomous_manifest),
    path("<int:pk>/autonomous/agents/", ag.agents),
    path("<int:pk>/autonomous/plan/", ag.agent_plan),
    path("<int:pk>/autonomous/authorize/", ag.agent_authorize),
    path("<int:pk>/autonomous/run/", ag.agent_execute),
    path("<int:pk>/autonomous/recover/", ag.agent_recover),
    path("<int:pk>/agents/workflow/", ag.agent_workflow),
    path("<int:pk>/agents/n8n/", ag.agent_n8n),
    path("<int:pk>/twin/graph/", tw.graphs),
    path("<int:pk>/rag/export/", rg.export_vectors),
    path("<int:pk>/fabric/sources/<int:sid>/push/", fb.source_push),
    path("<int:pk>/agents/", ag.agents),
    path("<int:pk>/agents/plan/", ag.agent_plan),
    path("<int:pk>/agents/authorize/", ag.agent_authorize),
    path("<int:pk>/agents/execute/", ag.agent_execute),
    path("<int:pk>/agents/resume/", ag.agent_resume),
    path("<int:pk>/agents/approve/", ag.agent_approve),
    path("<int:pk>/agents/approvals/", ag.approvals),
    path("<int:pk>/agents/recover/", ag.agent_recover),
    path("<int:pk>/agents/cancel/", ag.agent_cancel),
    path("<int:pk>/agents/runs/", ag.runs),
    path("<int:pk>/agents/runs/<int:run_id>/", ag.run_detail),
    path("<int:pk>/agents/tools/", ag.tool_registry),
    path("<int:pk>/agents/tools/<str:name>/govern/", ag.tool_govern),
    path("<int:pk>/agents/mcp/", ag.mcp_servers),
    path("<int:pk>/agents/mcp/<int:sid>/discover/", ag.mcp_discover),
    path("<int:pk>/agents/<int:aid>/", ag.agent_detail),
    path("<int:pk>/agents/<int:aid>/memory/", ag.agent_memory),
    path("<int:pk>/twin/", tw.twin),
    path("<int:pk>/twin/events/", tw.events),
    path("<int:pk>/twin/processes/", tw.processes),
    path("<int:pk>/twin/assets/", tw.assets),
    path("<int:pk>/twin/rules/", tw.rules),
    path("<int:pk>/twin/rules/<int:rid>/", tw.rule_detail),
    path("<int:pk>/twin/simulate/", tw.simulate),
    path("<int:pk>/twin/entities/<int:eid>/history/", tw.entity_history),
    path("<int:pk>/fabric/", fb.snapshot),
    path("<int:pk>/fabric/sync/", fb.sync_all),
    path("<int:pk>/fabric/sources/", fb.sources),
    path("<int:pk>/fabric/sources/<int:sid>/", fb.source_detail),
    path("<int:pk>/fabric/sources/<int:sid>/test/", fb.source_test),
    path("<int:pk>/fabric/sources/<int:sid>/discover/", fb.source_discover),
    path("<int:pk>/fabric/sources/<int:sid>/sync/", fb.source_sync),
    path("<int:pk>/fabric/sources/<int:sid>/suggest-mapping/", fb.suggest_mapping),
    path("<int:pk>/fabric/sources/<int:sid>/upload/", fb.source_upload),
    path("<int:pk>/fabric/runs/", fb.runs),
    path("<int:pk>/fabric/entities/", fb.entities),
    path("<int:pk>/fabric/entities/<int:eid>/", fb.entity_detail),
    path("<int:pk>/fabric/entities/<int:eid>/lineage/", fb.entity_lineage),
    path("<int:pk>/fabric/events/", fb.events),
    path("<int:pk>/fabric/suggestions/", fb.suggestions),
    path("<int:pk>/fabric/suggestions/<int:sid>/decide/", fb.suggestion_decide),
    path("<int:pk>/fabric/drift/", fb.drift),
    path("<int:pk>/fabric/drift/<int:did>/", fb.drift_decide),
    path("<int:pk>/fabric/sparql/", fb.fabric_sparql),
    path("<int:pk>/fabric/export/", fb.fabric_export),
    path("<int:pk>/fabric/", fb.snapshot),
    path("<int:pk>/fabric/sync/", fb.sync_all),
    path("<int:pk>/fabric/sources/", fb.sources),
    path("<int:pk>/fabric/sources/<int:sid>/", fb.source_detail),
    path("<int:pk>/fabric/sources/<int:sid>/test/", fb.source_test),
    path("<int:pk>/fabric/sources/<int:sid>/discover/", fb.source_discover),
    path("<int:pk>/fabric/sources/<int:sid>/sync/", fb.source_sync),
    path("<int:pk>/fabric/sources/<int:sid>/suggest-mapping/", fb.suggest_mapping),
    path("<int:pk>/fabric/runs/", fb.runs),
    path("<int:pk>/fabric/entities/", fb.entities),
    path("<int:pk>/fabric/entities/<int:eid>/", fb.entity_detail),
    path("<int:pk>/fabric/entities/<int:eid>/lineage/", fb.entity_lineage),
    path("<int:pk>/fabric/events/", fb.events),
    path("<int:pk>/fabric/suggestions/", fb.suggestions),
    path("<int:pk>/fabric/suggestions/<int:sid>/decide/", fb.suggestion_decide),
    path("<int:pk>/fabric/drift/", fb.drift),
    path("<int:pk>/fabric/drift/<int:did>/", fb.drift_decide),
    path("<int:pk>/fabric/sparql/", fb.fabric_sparql),
    path("<int:pk>/fabric/export/", fb.fabric_export),
]

# Accept every route with and without the trailing slash: Next.js (and some proxies) strip it, and a Django
# APPEND_SLASH redirect would then loop against the host's rewrite.
urlpatterns = []
for _p in _routes:
    urlpatterns.append(_p)
    route = str(_p.pattern)
    if route.endswith("/"):
        urlpatterns.append(path(route[:-1], _p.callback))
