import { useState } from 'react';
import { alpha } from '@mui/material/styles';
import { Alert, Box, Button, Chip, List, ListItem, ListItemText, Stack, TextField, Tooltip, Typography } from '@mui/material';
import { DiffLines, KindGlyph, NoOntology, PageHeader, RoleNotice, Why, needs } from '../components/ui';
import { useWB } from '../context';
import { useOnt } from '../theme';

const SUGGESTIONS = ['Create an ontology for contract management', 'Connect Contract to Customer', 'Add class Vehicle under Asset', 'Add property price to Product as decimal', 'Rename Customer to Client'];

const describe = (o) => ({
  add_class: `Add class ${o.name}${o.parents?.length ? ` (under ${o.parents.join(', ')})` : ''}`,
  add_property: `Add property ${o.domain}.${o.name} : ${o.datatype}`,
  add_relationship: `Add relationship ${o.domain} —${o.name}→ ${o.range}`,
  rename_class: `Rename ${o.from} → ${o.to}`,
  delete_class: `Delete class ${o.name}`,
}[o.op] || JSON.stringify(o));
const opKind = (o) => ({ add_class: 'class', rename_class: 'class', delete_class: 'class', add_property: 'data', add_relationship: 'object' }[o.op] || 'ai');

export default function AssistantTab() {
  const { api, ontology, notify, canEdit, can, loadOntology, dirty } = useWB();
  const { kind } = useOnt();
  const [prompt, setPrompt] = useState('');
  const [prop, setProp] = useState(null);
  const [busy, setBusy] = useState(false);
  if (!ontology) return <NoOntology />;

  const ask = async (p = prompt) => {
    setBusy(true);
    try { setProp({ ...(await api.aiPropose(ontology.id, p)), prompt: p }); } catch (e) { notify(e.message, 'error'); } finally { setBusy(false); }
  };
  const apply = async () => {
    try { await api.aiApply(ontology.id, prop.ops); notify('Proposal applied to the draft ontology.', 'success'); setProp(null); setPrompt(''); await loadOntology(ontology.id); }
    catch (e) { notify(e.message, 'error'); }
  };

  return (
    <Box sx={{ p: { xs: 1.5, md: 3 }, overflow: 'auto', height: '100%' }}>
      <Box sx={{ maxWidth: 900 }}>
        <PageHeader kind="ai" eyebrow="AI Assistant" title="Describe a change, review the proposal"
          description="The assistant only proposes. You see exactly what would change, and nothing is written to the ontology until you approve it." />
        <RoleNotice cap="write">You can ask for proposals and review their diffs, but only an editor or higher can apply one.</RoleNotice>
        {dirty && <Alert severity="info" sx={{ mb: 1.5 }}>Save your unsaved edits first — proposals are computed against the saved ontology.</Alert>}
        <Stack direction="row" spacing={1}>
          <TextField fullWidth size="small" placeholder="e.g. Create an ontology for contract management" value={prompt} onChange={(e) => setPrompt(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && prompt && ask()} inputProps={{ 'aria-label': 'Describe a change' }} data-testid="assistant-input" />
          <Button variant="contained" disabled={!prompt || busy} onClick={() => ask()}>Propose</Button>
        </Stack>
        <Box sx={{ mt: 1.5 }}><Typography variant="caption" color="text.secondary" sx={{ mr: 1 }}>Try:</Typography>{SUGGESTIONS.map((s) => <Chip key={s} size="small" clickable variant="outlined" sx={{ mr: 0.5, mb: 0.5 }} label={s} onClick={() => { setPrompt(s); ask(s); }} />)}</Box>
        {prop && (
          <Box sx={{ mt: 2.5, p: 2, borderRadius: 2, border: `1.5px dashed ${alpha(kind.ai, 0.7)}`, bgcolor: alpha(kind.ai, 0.05) }} data-testid="proposal">
            <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" rowGap={0.5}>
              <KindGlyph kind="ai" size={16} />
              <Typography variant="subtitle1" component="h3">Proposal</Typography>
              <Chip size="small" color="warning" variant="outlined" label="Proposed — not applied" />
              <Tooltip title={prop.source === 'llm' ? 'Generated by a language model' : 'Generated by built-in rules, not a language model'}><Chip size="small" variant="outlined" label={prop.source === 'llm' ? 'AI model' : 'rule-based'} /></Tooltip>
            </Stack>
            {prop.notes.map((n) => <Alert key={n} severity="info" sx={{ mt: 1 }}>{n}</Alert>)}
            {prop.ops.length === 0 ? <Typography sx={{ mt: 1 }} color="text.secondary">No changes proposed.</Typography> : (
              <>
                <List dense>{prop.ops.map((o, i) => <ListItem key={i}><Box sx={{ mr: 1.25, display: 'flex' }}><KindGlyph kind={opKind(o)} size={14} /></Box><ListItemText primary={describe(o)} /></ListItem>)}</List>
                <Typography variant="overline" color="text.secondary">Diff</Typography>
                <DiffLines lines={prop.diff.lines} />
                <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1 }}>After applying: health {prop.validationAfter.health}/100 · {prop.validationAfter.errors} errors · {prop.validationAfter.warnings} warnings</Typography>
                <Stack direction="row" spacing={1} sx={{ mt: 2 }}>
                  <Why reason={needs(can, 'write') || (dirty ? 'Save your unsaved edits first.' : '')}><Button variant="contained" color="success" disabled={!canEdit || dirty} onClick={apply}>Approve & apply</Button></Why>
                  <Button onClick={() => setProp(null)}>Reject</Button>
                </Stack>
              </>
            )}
          </Box>
        )}
      </Box>
    </Box>
  );
}
